name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependicies
        run: npm ci
      - name: Demo
        run: |
          echo "Hello"
          echo branch=$(git branch)
